### ISSUE TITLE
Bridge example is incorrect

### ISSUE THREAD

**Issue by MattRiddell** [asterisk/node-ari-client#128]
The example has:

var bridge = ari.Bridge();
bridge.create(function (err, bridge) {});

But resources.js has:

/**
 *  Creates a new Bridge instance.
 *
 *  @memberof module:resources
 *  @method Bridge
 *  @param {Client} client - ARI client instance
 *  @param {string} id - Application identifier
 *  @param {Object} objValues - ownProperties to copy to instance
 *  @returns {module:resources~Bridge} bridge
 */
module.exports.Bridge = function (client, id, objValues) {
  var bridge = new Bridge(client, id, objValues);
  attachOperations.call(bridge);
  return bridge;
};

**Comment by samuelg** [comment]
This works because of https://github.com/asterisk/node-ari-client/blob/master/lib/client.js#L177. When calling the various resource creator functions against a client, the client will send itself along so there's no need for the user of the library of pass the client explicitly.

The resources should not be called directly. They should either be called via the functions exposed on the client instance, or received via an event from ARI.
