### ISSUE TITLE
Swagger needs to be updated

### ISSUE THREAD

**Issue by woopstar** [asterisk/node-ari-client#34]
Using this project, connection to a newly installed asterisk 13.6.0 gives the following error:

[ 'This API is using a deprecated version of Swagger!  Please see http://github.com/wordnik/swagger-core/wiki for more info' ]

**Comment by samuelg** [comment]
As this is not something we can fix in node-ari-client itself I'm closing this. This issue is dependent on Asterisk updating its version of Swagger. If this is an issue for you (I've not run into compatibility issues yet connecting to an older version of the Swagger spec), please open an issue on https://issues.asterisk.org as this is the correct place to get this resolved.
