### ISSUE TITLE
how to get call originate event

### ISSUE THREAD

**Issue by mpbanna** [asterisk/node-ari-client#77]
how to get current status of a call originate in ARI,means staus of call-originated is at -> local end is ringing OR remote end is ringing OR remote end is busy etc.

**Comment by samuelg** [comment]
The ```ChannelStateChange``` event on a channel is what you need for this.

The callback you provide should have the following signature:

```js
function (event, channel) {
  // channel.state will contain the state of the channel
}
```

Please note that you will have to subscribe to early channel events using the following:

```js
client.applications.subscribe({
  applicationName: 'name',  // replace with your application name
  eventSource: 'channel:id'  // replace with your channel ID
})
```

If you use originate, you can only subscribe after you fire the origination, which means you can potentially miss some early events due to timing issues. It would be better to use ```client.channels.create``` followed by ```client.channels.dial``` for this. Using create+dial will auto subscribe to early channel events as well.

**Comment by mpbanna** [comment]
Thank you for solution.
